### ISSUE TITLE
generation

### ISSUE THREAD

**Issue by mattben** [webshootertk/webshooter#14]
currently webshooter creates a new site from one of three repos. this is a slowly failing idea.

we currently need to update the _config.yml files in all three jekyll sites... and creating new styles is limiting. 

Step 1:Change all three jekyll repos with a different markdown

remove

```
markdown: redcarpet    
  redcarpet:    
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]`
highlighter: true
```

add

`markdown: kramdown`

Step 2: re engine a way that webshooter runs the command jekyll new $SHORTNAME and then does a git pull on the styles repo and builds the site
